
CFLAGS=-Wall -g -pedantic

all:
	gcc $(CFLAGS)  chuckcotrill_byteorder.c -o chuckcotrill_byteorder
	gcc $(CFLAGS)  byte_explore.c -o byte_explore

clean:
	rm -rf chuckcotrill_byteorder
	rm -rf byte_explore
	rm -rf out_be.io
	rm -rf out_le.io
